# Week 5: Deep Neural Networks

## Dropout

In [4]:
%%time
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme()

print(torch.cuda.is_available())

False
CPU times: user 588 µs, sys: 163 µs, total: 751 µs
Wall time: 758 µs


In [5]:
torch.manual_seed(1)

In [6]:
from torch import nn, optim

class Net(nn.Module):
    def __init__(self, D_in, hidden, D_out,p=0):
        super(Net, self).__init__()
        self.drop = nn.Dropout(p=p)
        self.linear1 = nn.Linear(D_in, hidden)
        self.linear2 = nn.Linear(hidden,hidden)
        self.linear3 = nn.Linear(hidden, D_out)
    def forward(self, x):
        x = torch.relu(self.linear1(x))
        x = self.drop(x)
        x = torch.relu(self.linear2(x))
        x = self.drop(x)
        x = self.linear3(x)
        return x

## Initializing weights

In [9]:
linear = nn.Linear(2,3)
linear.weight

Parameter containing:
tensor([[ 0.6181,  0.2200],
        [-0.2633, -0.4271],
        [-0.1185, -0.3050]], requires_grad=True)

In [10]:
torch.nn.init.xavier_uniform_(linear.weight)
linear.weight

Parameter containing:
tensor([[ 0.5954, -1.0709],
        [ 0.6791,  0.3060],
        [ 1.0391,  0.7231]], requires_grad=True)

In [11]:
torch.nn.init.kaiming_uniform_(linear.weight, nonlinearity="relu")
linear.weight

Parameter containing:
tensor([[-1.5781, -1.6468],
        [-0.8354,  1.5209],
        [-0.2885,  0.7412]], requires_grad=True)