# Week 4: Neural Networks

## Softmax Regression 

In [1]:
%%time
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme()

print(torch.cuda.is_available())

False
CPU times: user 2.38 s, sys: 757 ms, total: 3.13 s
Wall time: 4.21 s


In [2]:
torch.manual_seed(1)

In [3]:
from torch import nn, optim

class Softmax(nn.Module):
    def __init__(self, input_size, output_size):
        super(Softmax, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        return self.linear(x)

In [4]:
model = Softmax(2,3)

In [5]:
X = torch.tensor([[1.0, 2.0]])
X

tensor([[1., 2.]])

In [6]:
z = model(X)
z

tensor([[-0.4053,  0.8864,  0.2807]], grad_fn=<AddmmBackward0>)

In [8]:
_, yhat = z.max(1)
yhat

tensor([1])

In [9]:
X = torch.tensor([[1.0, 1.0], [1.0,2.0],[1.0,3.0]])
z = model(X)
_, yhat = z.max(1)
yhat

tensor([1, 1, 1])