# Week 3: Neural Networks

## Neural Network

In [1]:
%%time
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme()

print(torch.cuda.is_available())

False
CPU times: user 1.56 s, sys: 482 ms, total: 2.04 s
Wall time: 2.83 s


In [2]:
torch.manual_seed(1)

In [5]:
from torch import nn, optim

class Net(nn.Module):
    def __init__(self, D_in, H, D_out):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(D_in, H)
        self.linear2 = nn.Linear(H, D_out)
    def forward(self, x):
        x = torch.sigmoid(self.linear1(x))
        x = torch.sigmoid(self.linear2(x))
        return x

In [6]:
model = Net(1, 2, 1)

In [7]:
X = torch.tensor([[0.0]])
X

tensor([[0.]])

In [8]:
yhat = model(X)
yhat

tensor([[0.4538]], grad_fn=<SigmoidBackward0>)

In [9]:
X = torch.tensor([[1.0], [2.0],[3.0]])
z = model(X)
yhat = model(X)
yhat

tensor([[0.4216],
        [0.3915],
        [0.3664]], grad_fn=<SigmoidBackward0>)

In [10]:
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.5153],
                      [-0.4414]])),
             ('linear1.bias', tensor([-0.1939,  0.4694])),
             ('linear2.weight', tensor([[-0.6657,  0.4241]])),
             ('linear2.bias', tensor([-0.1455]))])

In [11]:
model = nn.Sequential(nn.Linear(1,2), nn.Sigmoid(), nn.Linear(2,1), nn.Sigmoid())
model

Sequential(
  (0): Linear(in_features=1, out_features=2, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Sigmoid()
)

In [25]:
def train(Y,X, model, optimizer, criterion, epochs=1000):
    cost = []
    total = 0
    for epoch in range(epochs):
        total = 0
        for y, x in zip(Y,X):
            yhat = model(x)
            loss = criterion(yhat, y)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            total += loss.item()
        cost.append(total)
    return cost

In [26]:
X = torch.arange(-20, 20, 1).view(-1, 1).type(torch.FloatTensor)
Y = torch.zeros(X.shape)
Y[(X[:,0] > -4) & (X[:,0] < 4)] = 1.0


In [27]:
model = Net(1,2,1)
optimizer = optim.SGD(model.parameters(), lr = 0.01)
criterion = nn.BCELoss()
cost = train(Y,X, model, optimizer, criterion)
cost

[20.963064551353455,
 20.48059743642807,
 20.103012412786484,
 19.80510926246643,
 19.56821572780609,
 19.378392815589905,
 19.22515019774437,
 19.100531339645386,
 18.998454988002777,
 18.914238169789314,
 18.844249367713928,
 18.785655289888382,
 18.736230075359344,
 18.69421660900116,
 18.658220037817955,
 18.62712524831295,
 18.600039571523666,
 18.57624463737011,
 18.555159032344818,
 18.53630931675434,
 18.519312992691994,
 18.503854006528854,
 18.489674732089043,
 18.47656226158142,
 18.46434062719345,
 18.45286650955677,
 18.442016065120697,
 18.431690737605095,
 18.42180524766445,
 18.412288784980774,
 18.403082340955734,
 18.394133031368256,
 18.38540083169937,
 18.376847609877586,
 18.3684424161911,
 18.360157012939453,
 18.351970806717873,
 18.343861505389214,
 18.33581107854843,
 18.327805995941162,
 18.319829881191254,
 18.311875253915787,
 18.303924471139908,
 18.295973539352417,
 18.28801128268242,
 18.280029594898224,
 18.27202147245407,
 18.263981819152832,
 18.255900