# Week 6: Convolution

## Convolution

In [3]:
%%time
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme()

print(torch.cuda.is_available())
torch.manual_seed(1)
from torch import nn

False
CPU times: user 5.63 ms, sys: 0 ns, total: 5.63 ms
Wall time: 4.65 ms


In [4]:
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

img = torch.zeros(1, 1, 5, 5)
img[0,0,:,2]=1
img

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

In [5]:
z = conv(img)
z

tensor([[[[ 0.1408, -0.3322,  0.2188],
          [ 0.1408, -0.3322,  0.2188],
          [ 0.1408, -0.3322,  0.2188]]]], grad_fn=<ConvolutionBackward0>)

## Max Pooling

In [6]:
maxpool = nn.MaxPool2d(2, stride=1)
maxpool

MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)

In [7]:
maxpool(img)

tensor([[[[0., 1., 1., 0.],
          [0., 1., 1., 0.],
          [0., 1., 1., 0.],
          [0., 1., 1., 0.]]]])

## Multiple Inputs and Outputs

In [8]:
conv = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3)
# tự gen 3 kernel cho ra 3 output
conv(img)

tensor([[[[ 0.3276, -0.0647, -0.0447],
          [ 0.3276, -0.0647, -0.0447],
          [ 0.3276, -0.0647, -0.0447]],

         [[ 0.0157,  0.0734,  0.2065],
          [ 0.0157,  0.0734,  0.2065],
          [ 0.0157,  0.0734,  0.2065]],

         [[-0.0728,  0.1110, -0.4815],
          [-0.0728,  0.1110, -0.4815],
          [-0.0728,  0.1110, -0.4815]]]], grad_fn=<ConvolutionBackward0>)

In [13]:
conv = nn.Conv2d(in_channels=2, out_channels=1, kernel_size=3)
# dùng 2 kernel rồi sum lại cho thành 1
conv(torch.zeros(1, 2, 5, 5))

tensor([[[[0.1469, 0.1469, 0.1469],
          [0.1469, 0.1469, 0.1469],
          [0.1469, 0.1469, 0.1469]]]], grad_fn=<ConvolutionBackward0>)

In [14]:
conv = nn.Conv2d(in_channels=2, out_channels=3, kernel_size=3)
# dùng 6 kernel, 2 kernel x 2 input rồi sum lại thành 1 out, làm 3 lần thành 3 out
conv(torch.zeros(1, 2, 5, 5))

tensor([[[[-0.1274, -0.1274, -0.1274],
          [-0.1274, -0.1274, -0.1274],
          [-0.1274, -0.1274, -0.1274]],

         [[ 0.0843,  0.0843,  0.0843],
          [ 0.0843,  0.0843,  0.0843],
          [ 0.0843,  0.0843,  0.0843]],

         [[-0.0907, -0.0907, -0.0907],
          [-0.0907, -0.0907, -0.0907],
          [-0.0907, -0.0907, -0.0907]]]], grad_fn=<ConvolutionBackward0>)