# Week 1: Tensor

## Tensor 2D

In [1]:
%%time
import torch
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_theme()

print(torch.cuda.is_available())

False
CPU times: user 1.82 s, sys: 691 ms, total: 2.51 s
Wall time: 2.51 s


In [3]:
matrix_arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix_arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
torch_matrix = torch.tensor(matrix_arr)
torch_matrix


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
print("Type: ", type(torch_matrix))
print("Type: ", torch_matrix.type())
print("Size: ", torch_matrix.size())
print("Shape: ", torch_matrix.shape)
print("N-Dimension: ", torch_matrix.ndimension())
print("Num Elements: ", torch_matrix.numel())

Type:  <class 'torch.Tensor'>
Type:  torch.LongTensor
Size:  torch.Size([3, 3])
Shape:  torch.Size([3, 3])
N-Dimension:  2
Num Elements:  9


In [9]:
torch_matrix[1,2]

tensor(6)

In [11]:
torch_matrix[0,0:2]

tensor([1, 2])

In [12]:
torch_matrix[0:1,1:2]

tensor([[2]])

In [13]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8 ,9], [10, 11, 12]])

In [14]:
x + y

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [15]:
x * y

tensor([[ 7, 16, 27],
        [40, 55, 72]])

In [19]:
torch.mm(torch.transpose(x, 0, 1), y)

tensor([[47, 52, 57],
        [64, 71, 78],
        [81, 90, 99]])