# Week 1: Tensor

## Simple Dataset

In [1]:
%%time
import torch
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_theme()

print(torch.cuda.is_available())

False
CPU times: user 2.12 s, sys: 3.63 s, total: 5.75 s
Wall time: 5.75 s


In [6]:
from torch.utils.data import Dataset

class ToySet(Dataset):
    def __init__(self, length=100, transform=None):
        self.x = 2*torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

In [7]:
ds = ToySet()
ds

In [4]:
len(ds)

100

In [8]:
ds[0]

(tensor([2., 2.]), tensor([1.]))

In [9]:
ds.y

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [10]:
class AddMulTransform:
    def __init__(self, addx=1, muly=1):
        self.addx=addx
        self.muly=muly

    def __call__(self, sample: tuple):
        x = sample[0] + self.addx
        y = sample[1] * self.muly
        return (x, y)

In [11]:
a_m = AddMulTransform()

a_m(ds[0])

(tensor([3., 3.]), tensor([1.]))

In [12]:
ds2 = ToySet(transform=a_m)
ds2[0]

(tensor([3., 3.]), tensor([1.]))

In [15]:
ds3 = ToySet(transform=lambda x: (x[0]+5, x[1]+2))
ds3[0]

(tensor([7., 7.]), tensor([3.]))

In [16]:
class MulTransform:
    def __init__(self, muly=2):
        self.muly=muly

    def __call__(self, sample: tuple):
        x = sample[0]
        y = sample[1] * self.muly
        return (x, y)

In [17]:
from torchvision.transforms import Compose

transform = Compose([AddMulTransform(), MulTransform()])

ds4 = ToySet(transform=transform)
ds4[0]

(tensor([3., 3.]), tensor([2.]))